<a href="https://colab.research.google.com/github/kunjb-sao/Python-ML/blob/main/NLP_Steming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install nltk

In [ ]:
!pip install nltk
import nltk
from nltk.stem import WordNetLemmatizer

# Download 'wordnet' and 'punkt'
nltk.download('wordnet')
nltk.download('punkt')

word_lemm = WordNetLemmatizer()

sentence = "Walking The article discusses the challenges of global warming and highlights the importance of carbon capture and sequestration (CCS) technology as a response to climate change. It distinguishes between adaptation and mitigation efforts to address rising temperatures, emphasizing that most greenhouse gas emissions result from human activities, particularly the burning of fossil fuels. A recent study has raised concerns about the cost-effectiveness of CCS compared to renewable energy options."

punctuations = "?.;:!,,())"

sentence_words = nltk.word_tokenize(sentence)

for word in sentence_words:
    if word in punctuations:
        print(word)
        sentence_words.remove(word)

print(sentence_words)

for word in sentence_words:
    print(word_lemm.lemmatize(word))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.DataFrame({'x': ['apple orange', 'banana', 'apple', 'mango banana orange grapes apple', 'mango', 'grapes'], 'y': [1, 0, 0, 1, 0, 0 ]})

In [ ]:
df

x  y
0                      apple orange  1
1                            banana  0
2                             apple  0
3  mango banana orange grapes apple  1
4                             mango  0
5                            grapes  0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
model = CountVectorizer()

In [ ]:
bow = model.fit_transform(df['x'])

In [ ]:
model.vocabulary_

{'apple': 0, 'orange': 4, 'banana': 1, 'mango': 3, 'grapes': 2}

In [ ]:
bow[0].toarray()

array([[1, 0, 0, 0, 1]])

In [ ]:
bow[1].toarray()

array([[0, 1, 0, 0, 0]])

In [ ]:
bow[2].toarray()

array([[1, 0, 0, 0, 0]])

In [ ]:
model.transform(['mango banana banana orange grapes apple apple apple']).toarray()

array([[3, 2, 1, 1, 1]])

In [ ]:
df = pd.DataFrame({'x': ['apple orange', 'banana', 'apple', 'mango banana orange grapes apple'], 'y': [1, 0, 0, 1 ]})

In [ ]:
df = pd.DataFrame({'x': ["I like banana, don't like orange", 'I like only apple', 'I like all fruits', "I don't like any fruits"], 'y': [1, 0, 0, 1 ]})

In [ ]:
df

x  y
0  I like banana, don't like orange  1
1                 I like only apple  0
2                 I like all fruits  0
3           I don't like any fruits  1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
model = CountVectorizer(ngram_range=(1,2))

In [ ]:
ngram = model.fit_transform(df['x'])

In [ ]:
model.vocabulary_

{'like': 10,
 'banana': 5,
 'don': 7,
 'orange': 18,
 'like banana': 13,
 'banana don': 6,
 'don like': 8,
 'like orange': 15,
 'only': 16,
 'apple': 4,
 'like only': 14,
 'only apple': 17,
 'all': 0,
 'fruits': 9,
 'like all': 11,
 'all fruits': 1,
 'any': 2,
 'like any': 12,
 'any fruits': 3}

In [ ]:
vocab = model.vocabulary_

In [ ]:
{k: v for k, v in sorted(vocab.items(), key=lambda item: item[1])}

{'all': 0,
 'all fruits': 1,
 'any': 2,
 'any fruits': 3,
 'apple': 4,
 'banana': 5,
 'banana don': 6,
 'don': 7,
 'don like': 8,
 'fruits': 9,
 'like': 10,
 'like all': 11,
 'like any': 12,
 'like banana': 13,
 'like only': 14,
 'like orange': 15,
 'only': 16,
 'only apple': 17,
 'orange': 18}

In [ ]:
ngram[0].toarray()

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1]])

In [ ]:
ngram[1].toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0]])

In [ ]:
model.transform(['I like mango']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])